services:
  influxdb2:
    image: influxdb:2-alpine
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: stracked
      DOCKER_INFLUXDB_INIT_BUCKET: stracked

  app:
    build:
      context: .
      args:
        MAXMIND_ACCOUNT_ID: ${MAXMIND_ACCOUNT_ID}
        MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    ports:
      - 8000:8000
    links:
      - influxdb2
